# Generated by Django 2.2.7 on 2020-09-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='user_address',
        ),
    ]
